// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'originMenu.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OriginMenu _$OriginMenuFromJson(Map<String, dynamic> json) => OriginMenu(
      cateCD: json['cateCD'] as String?,
      delYN: json['delYN'] as String?,
      regUSER: json['regUSER'] as String?,
      regDT: json['regDT'] as String?,
      modUSER: json['modUSER'] as String?,
      modDT: json['modDT'] as String?,
      content: json['content'] as String?,
      cateTYPE: json['cateTYPE'] as String?,
      proSEQ: json['proSEQ'] as int?,
      viewYN: json['viewYN'] as String?,
      infoTABLE: json['infoTABLE'] as String?,
      fileTABLE: json['fileTABLE'] as String?,
      cateTABLE: json['cateTABLE'] as String?,
      cardTABLE: json['cardTABLE'] as String?,
      msrSEQ: json['msrSEQ'] as int?,
      webIMAGEWEBVIEW: json['webIMAGEWEBVIEW'] as String?,
      webIMAGETABVIEW: json['webIMAGETABVIEW'] as String?,
      webIMAGEMOBVIEW: json['webIMAGEMOBVIEW'] as String?,
      productENGNM: json['productENGNM'] as String?,
      productCD: json['productCD'] as String?,
      productNM: json['productNM'] as String?,
      fileNAME: json['fileNAME'] as String?,
      filePATH: json['filePATH'] as String?,
      cateNAME: json['cateNAME'] as String?,
      recommend: json['recommend'] as String?,
      kcal: json['kcal'] as String?,
      fat: json['fat'] as String?,
      nutTABLE: json['nutTABLE'] as String?,
      newSDATE: json['newSDATE'] as String?,
      newEDATE: json['newEDATE'] as String?,
      sellCAT: json['sellCAT'] as String?,
      giftVALUE: json['giftVALUE'] as String?,
      hotYN: json['hotYN'] as String?,
      price: json['price'] as String?,
      soldOUT: json['soldOUT'] as String?,
      frontVIEWYN: json['frontVIEWYN'] as String?,
      viewSDATE: json['viewSDATE'] as String?,
      viewEDATE: json['viewEDATE'] as String?,
      noteTYPE: json['noteTYPE'] as String?,
      youtubeCODE: json['youtubeCODE'] as String?,
      newicon: json['newicon'] as String?,
      recomm: json['recomm'] as String?,
      fileMASTER: json['fileMASTER'] as String?,
      thumbnail: json['thumbnail'] as String?,
      imgORDER: json['imgORDER'] as String?,
      standard: json['standard'] as String?,
      unit: json['unit'] as String?,
      satFAT: json['satFAT'] as String?,
      transFAT: json['transFAT'] as String?,
      cholesterol: json['cholesterol'] as String?,
      sugars: json['sugars'] as String?,
      chabo: json['chabo'] as String?,
      protein: json['protein'] as String?,
      sodium: json['sodium'] as String?,
      caffeine: json['caffeine'] as String?,
      allergy: json['allergy'] as String?,
      kcalL: json['kcalL'] as String?,
      fatL: json['fatL'] as String?,
      satFATL: json['satFATL'] as String?,
      transFATL: json['transFATL'] as String?,
      cholesterolL: json['cholesterolL'] as String?,
      sugarsL: json['sugarsL'] as String?,
      chaboL: json['chaboL'] as String?,
      proteinL: json['proteinL'] as String?,
      sodiumL: json['sodiumL'] as String?,
      caffeineL: json['caffeineL'] as String?,
      msrSEQ2: json['msrSEQ2'] as String?,
      webNEW: json['webNEW'] as String?,
      appIMAGE: json['appIMAGE'] as String?,
      webCARDBIRTH: json['webCARDBIRTH'] as String?,
      cardYEAR: json['cardYEAR'] as String?,
      cardMONTH: json['cardMONTH'] as String?,
      egiftCARDYN: json['egiftCARDYN'] as String?,
      pairTABLE: json['pairTABLE'] as String?,
      subVIEW: json['subVIEW'] as String?,
      fCATECD: json['fCATECD'] as String?,
      pcateCD: json['pcateCD'] as String?,
      allCATECD: json['allCATECD'] as String?,
      imgUPLOADPATH: json['imgUPLOADPATH'] as String?,
      premier: json['premier'] as String?,
      searchDATETYPE: json['searchDATETYPE'] as String?,
      searchSTARTDATE: json['searchSTARTDATE'] as String?,
      searchENDDATE: json['searchENDDATE'] as String?,
      search1CATE: json['search1CATE'] as String?,
      search2CATE: json['search2CATE'] as String?,
      search3CATE: json['search3CATE'] as String?,
      searchSALETYPE: json['searchSALETYPE'] as String?,
      searchVIEWYN: json['searchVIEWYN'] as String?,
      searchKEY: json['searchKEY'] as String?,
      searchVALUE: json['searchVALUE'] as String?,
      themeSEARCH: json['themeSEARCH'] as String?,
      pageINDEX: json['pageINDEX'] as int?,
      pageUNIT: json['pageUNIT'] as int?,
      pageSIZE: json['pageSIZE'] as int?,
      firstINDEX: json['firstINDEX'] as int?,
      lastINDEX: json['lastINDEX'] as int?,
      recordCOUNTPERPAGE: json['recordCOUNTPERPAGE'] as int?,
      totalCNT: json['totalCNT'] as int?,
      rnum: json['rnum'] as int?,
    );

Map<String, dynamic> _$OriginMenuToJson(OriginMenu instance) =>
    <String, dynamic>{
      'cateCD': instance.cateCD,
      'delYN': instance.delYN,
      'regUSER': instance.regUSER,
      'regDT': instance.regDT,
      'modUSER': instance.modUSER,
      'modDT': instance.modDT,
      'content': instance.content,
      'cateTYPE': instance.cateTYPE,
      'proSEQ': instance.proSEQ,
      'viewYN': instance.viewYN,
      'infoTABLE': instance.infoTABLE,
      'fileTABLE': instance.fileTABLE,
      'cateTABLE': instance.cateTABLE,
      'cardTABLE': instance.cardTABLE,
      'msrSEQ': instance.msrSEQ,
      'webIMAGEWEBVIEW': instance.webIMAGEWEBVIEW,
      'webIMAGETABVIEW': instance.webIMAGETABVIEW,
      'webIMAGEMOBVIEW': instance.webIMAGEMOBVIEW,
      'productENGNM': instance.productENGNM,
      'productCD': instance.productCD,
      'productNM': instance.productNM,
      'fileNAME': instance.fileNAME,
      'filePATH': instance.filePATH,
      'cateNAME': instance.cateNAME,
      'recommend': instance.recommend,
      'kcal': instance.kcal,
      'fat': instance.fat,
      'nutTABLE': instance.nutTABLE,
      'newSDATE': instance.newSDATE,
      'newEDATE': instance.newEDATE,
      'sellCAT': instance.sellCAT,
      'giftVALUE': instance.giftVALUE,
      'hotYN': instance.hotYN,
      'price': instance.price,
      'soldOUT': instance.soldOUT,
      'frontVIEWYN': instance.frontVIEWYN,
      'viewSDATE': instance.viewSDATE,
      'viewEDATE': instance.viewEDATE,
      'noteTYPE': instance.noteTYPE,
      'youtubeCODE': instance.youtubeCODE,
      'newicon': instance.newicon,
      'recomm': instance.recomm,
      'fileMASTER': instance.fileMASTER,
      'thumbnail': instance.thumbnail,
      'imgORDER': instance.imgORDER,
      'standard': instance.standard,
      'unit': instance.unit,
      'satFAT': instance.satFAT,
      'transFAT': instance.transFAT,
      'cholesterol': instance.cholesterol,
      'sugars': instance.sugars,
      'chabo': instance.chabo,
      'protein': instance.protein,
      'sodium': instance.sodium,
      'caffeine': instance.caffeine,
      'allergy': instance.allergy,
      'kcalL': instance.kcalL,
      'fatL': instance.fatL,
      'satFATL': instance.satFATL,
      'transFATL': instance.transFATL,
      'cholesterolL': instance.cholesterolL,
      'sugarsL': instance.sugarsL,
      'chaboL': instance.chaboL,
      'proteinL': instance.proteinL,
      'sodiumL': instance.sodiumL,
      'caffeineL': instance.caffeineL,
      'msrSEQ2': instance.msrSEQ2,
      'webNEW': instance.webNEW,
      'appIMAGE': instance.appIMAGE,
      'webCARDBIRTH': instance.webCARDBIRTH,
      'cardYEAR': instance.cardYEAR,
      'cardMONTH': instance.cardMONTH,
      'egiftCARDYN': instance.egiftCARDYN,
      'pairTABLE': instance.pairTABLE,
      'subVIEW': instance.subVIEW,
      'fCATECD': instance.fCATECD,
      'pcateCD': instance.pcateCD,
      'allCATECD': instance.allCATECD,
      'imgUPLOADPATH': instance.imgUPLOADPATH,
      'premier': instance.premier,
      'searchDATETYPE': instance.searchDATETYPE,
      'searchSTARTDATE': instance.searchSTARTDATE,
      'searchENDDATE': instance.searchENDDATE,
      'search1CATE': instance.search1CATE,
      'search2CATE': instance.search2CATE,
      'search3CATE': instance.search3CATE,
      'searchSALETYPE': instance.searchSALETYPE,
      'searchVIEWYN': instance.searchVIEWYN,
      'searchKEY': instance.searchKEY,
      'searchVALUE': instance.searchVALUE,
      'themeSEARCH': instance.themeSEARCH,
      'pageINDEX': instance.pageINDEX,
      'pageUNIT': instance.pageUNIT,
      'pageSIZE': instance.pageSIZE,
      'firstINDEX': instance.firstINDEX,
      'lastINDEX': instance.lastINDEX,
      'recordCOUNTPERPAGE': instance.recordCOUNTPERPAGE,
      'totalCNT': instance.totalCNT,
      'rnum': instance.rnum,
    };
